# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 04:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('type', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.FloatField(null=True)),
                ('int_value', models.BigIntegerField(null=True)),
                ('json_value', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('binary_value', models.BinaryField(null=True)),
                ('datetime_value', models.DateTimeField(null=True)),
                ('string_value', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('serial', models.CharField(default='', max_length=255)),
                ('date', models.DateTimeField(null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualiser.Country')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualiser.StatisticItem')),
            ],
        ),
    ]
